pub const KERNEL_UPDATE_PROTOCOL_VERSION: u32 = 2;

pub const MSG_KERNEL_UPDATE_REQUEST: &str = crate::brand::BRIDGE_MSG_KERNEL_UPDATE_REQUEST;

pub const MSG_KERNEL_UPDATE_RESULT: &str = crate::brand::BRIDGE_MSG_KERNEL_UPDATE_RESULT;

pub const MSG_KERNEL_UPDATE_PROGRESS: &str = crate::brand::BRIDGE_MSG_KERNEL_UPDATE_PROGRESS;

pub const CMD_KERNEL_UPDATE_APPLY: &str = "kernel_update_apply";

pub const KERNEL_UPDATE_BUDGET_MS: u64 = 17 * 60 * 1000;

pub const KERNEL_UPDATE_GRACE_MS: u64 = 60 * 1000;

pub const KERNEL_UPDATE_MAX_WAIT_MS: u64 = KERNEL_UPDATE_BUDGET_MS + KERNEL_UPDATE_GRACE_MS;

